# Generated by Django 5.0.4 on 2025-06-07 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_eventrsvp_alter_event_options_alter_sermon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrsvp',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_rsvp'),
        ),
    ]
