# Generated by Django 5.0.4 on 2025-06-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_eventrsvp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sermon_series/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_next_sunday', models.BooleanField(default=True)),
                ('special_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Upcoming Sermons',
                'ordering': ['sermon__date_preached'],
            },
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date_preached'], 'verbose_name_plural': 'Sermons'},
        ),
        migrations.RemoveIndex(
            model_name='sermon',
            name='church_serm_date_55b1ce_idx',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='bible_verse',
            new_name='bible_passage',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='date',
            new_name='date_preached',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='scripture_text',
            new_name='sermon_notes',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='slides',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='topic',
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_type',
            field=models.CharField(choices=[('sunday', 'Sunday Service'), ('bible_study', 'Bible Study'), ('special', 'Special Service'), ('conference', 'Conference'), ('other', 'Other')], default='sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='church.sermonseries'),
        ),
        migrations.AddIndex(
            model_name='sermon',
            index=models.Index(fields=['-date_preached'], name='church_serm_date_pr_f663d8_idx'),
        ),
        migrations.AddField(
            model_name='upcomingsermon',
            name='sermon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming', to='church.sermon'),
        ),
    ]
