# Generated by Django 5.0.4 on 2025-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_sermonseries_upcomingsermon_alter_sermon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ministries/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
